<a href="https://colab.research.google.com/github/manojach87/miscellaneous/blob/master/List_and_Ellipsis%5Ba_k_a_three_dots%5D_Object.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

In [4]:
a=[[0,1,2,3],[4,5,6,7],[8,9,10,11]]
a[1][1]
a[:][:]
a[:]
a[:1]
a[2:3]

[[8, 9, 10, 11]]

In [5]:
b=np.array(a)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
b[...]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**Selecting first row, all cols** using Ellipsis object

In [7]:
b[0,...]

array([0, 1, 2, 3])

**Selecting second column, all rows** using Ellipsis object

In [8]:
b[...,1] 

array([1, 5, 9])